[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "24.4.1"
  NPM_FLAGS = "--prefix=/opt/buildhome/node_modules/.bin"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "functions"

# Redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 